### ISSUE TITLE
Tag releases here on GitHub

### ISSUE THREAD

**Issue by szepeviktor** [blockifywp/theme#16]
I cannot send tags in PR-s.
May I send `git tag v...` commands here in this issue?

https://github.com/blockifywp/theme/blob/092fffbcc10b591482488df656ebf97b9ac07f0a/readme.txt#L62-L354

**Comment by seothemes** [comment]
Sure can, whatever is easiest for you.

Just a heads up that I’m currently separating all of the functionality currently in this theme (PHP includes, CSS & JS) and moving it to the Blockify plugin - which will then be installed back in this theme as a composer package.

That would allow it to be reused as a theme framework by others and for any future themes (or plugins). 

Can you see any issues with this idea?

**Comment by szepeviktor** [comment]
Dependency management is simply missing from WordPress. 🤦🏻‍♂️ That is hard!

It would be nice supporting people [managing WordPress with Composer](https://github.com/szepeviktor/composer-managed-wordpress). For example me :)

`if (! class_exist('Blockify plugin')) require __DIR__ . 'vendor/autoload.php';`

**Comment by seothemes** [comment]
Hard problem to solve for sure, would be nice to have a cleaner way.

Agreed, it would also allow you to white label the theme while still receiving updates for the framework.

Perfect, that's what I've ended up with. Now seeing if it's possible to have the conditions in the plugin itself, to keep the theme as clean as possible and prevent further errors.

**Comment by seothemes** [comment]
Sharing this discussion here as well for future reference https://github.com/blockifywp/plugin/issues/4#issuecomment-1250689310

**Comment by szepeviktor** [comment]
```bash
git tag v0.0.8 ded3e00a5fa054af11962e8806ff67056885979a
git tag v0.0.9 ca82d6c356347c2de5cd7d559f435a6dc0b25929
git tag v0.0.11 deb00dcb33df54cb5abd284e9d8a51238f1dd8a7
git tag v0.0.12 f3cc249d538c80508cf98592c840b630e5dcbd0d
git tag v0.0.13 cf713ff756d057ad2534c7a212d29a277c153297
git tag v0.0.23 90689455618e2bde521759f4d49f19d4c6ec1c01
git tag v0.0.26 adde357d23caff5001bde7ec5be8a3ba4db4fbc3
git tag v0.0.27 5f34295fd0b109bd78d8ce46456aacbb20076ffa
git tag v0.0.28 efe0e75fbec79bcd3e9af21c2df245d332fe4dc2
git tag v0.0.29 1780b8306cdb0154b811496ff7f076617f79a52c
git tag v0.0.30 979f5f68fc1609d3a38ac2f71373f9a40dd2914b
git tag v0.0.31 ac8d0451954c0530f30594d7451ef1fdafd74b76
git tag v0.0.32 924efbe908a976a7632f2eed3ad0cd71216570d2
git tag v0.0.33 38d528800195c76e213f1939c4e60d67800dc1e9
git tag v0.1.0 118b68911c407033b58fe31ccf4c7d7aa7f0ee44
git tag v0.1.1 89c788b78442b0b2efb72df9e6df9a4023cabb4d
git tag v0.1.2 9389cca308c59d113ffad041bc7b868693236cd1
git tag v0.1.3 8a3f74bab77f754511942953d23084b87fa23357
git tag v0.1.4 e91467b58b15cae81d048ba61aed34caf48442a0
git tag v0.2.1 4e3898d161c8653851b7382930e42de22761a186
git tag v0.3.0 742222946dd635577498a4891aa0ac376a83fa54
git tag v0.3.1 c82c9e08e950be9c748f2942df6d96cf8c7f9938
git tag v0.3.2 97a67a3fcd27100053cbebe6115c917ff97517da
git tag v0.3.3 9aa1fb30e0db9a0fa72c0a4a6cc152191257442c
git tag v0.3.4 b93f7d64963ad88fafe9084747868a55b2f0394b
git tag v0.3.5 8123a748c03a8aa9c187cf203c0a2f2fe366b125
git tag v0.3.8 8ffdd5da0c87d4c052718b9b0eb6600c092914ca
git tag v0.3.11 d9e0afc0c0983b756321599b50eb439e601942aa
git tag v0.3.12 a079653c3bf23545490a8e47775fa060d19b46e9
```

A public release checklist would be nice: tag, build, deploy, announce (blog, Twitter, Wiki)

**Comment by seothemes** [comment]
Have pushed the tags, is there a specific place I should put the checklist?

**Comment by seothemes** [comment]
How were you able to generate that list of tags with the relevant commits? That's awesome

**Comment by szepeviktor** [comment]
> How were you able to generate that list of tags

I have a limb called "hands" :)

**Comment by szepeviktor** [comment]
> is there a specific place I should put the checklist?

No. I'm good at theories but I'm not a pioneer!

**Comment by seothemes** [comment]
Haha, good to know! I was hoping you didn’t have to do that manually. 

Ok, that’s the plan. Will tag future releases.
