### ISSUE TITLE
Package type "wordpress-dropin" breaking workflow

### ISSUE THREAD

**Issue by seothemes** [blockifywp/theme#17]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/24793388/190981819-b329edf1-4b45-4038-9391-b5645ec676aa.png">

**Comment by seothemes** [comment]
https://github.com/aaemnnosttv/wp-sqlite-db/issues/30

**Comment by seothemes** [comment]
@szepeviktor did you see this one? Looks like the way I have the Pest integration tests setup is not compatible :/

Wondering if adding CI to this theme is necessary, running into a ton of issues. Not sure I will ever have time to get it working.

**Comment by seothemes** [comment]
https://github.com/dingo-d/wp-pest-integration-test-setup#running-the-package-in-ci-pipelines

**Comment by szepeviktor** [comment]
Try adding `composer/installers` package.

**Comment by szepeviktor** [comment]
BTW When running test of a WordPress theme, a WordPress core, theme and plugins and drop-ins should be installed in a subdirectory. e.g. `.build/wordpress/`

**Comment by seothemes** [comment]
Ok, I have removed that from the workflow and commented out the pest step for now 58bb403147f12df23a5f943f7c22dc65941943ff

Trying to get all the other jobs passing first, then will go back to pest.

What is your recommendation for coding standards? I incorrectly assumed that WP would have improved. Refactoring everything back to php 5 would be a shame.

**Comment by szepeviktor** [comment]
> What is your recommendation for coding standards?

There no answer :(
The base should be PSR-12.
This is a useful frankenstein: https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset

**Comment by szepeviktor** [comment]
Many WordPress people follow WPCS blindly - but that is not useful for professionals. Its own documentation says so.

**Comment by szepeviktor** [comment]
This coding style is so emotional. I better shut my mouth.

**Comment by seothemes** [comment]
Fixed 2ffe52116269937c9f69bb03e678dbff6944f850
