### ISSUE TITLE
Fatal error after upgrade to 1.0.0

### ISSUE THREAD

**Issue by davidmadon** [blockifywp/theme#32]
Hi!

Im getting a fatal error in the front-end and in the editor on one of my pages after upgrading Blockify to 1.0.0:

![image](https://user-images.githubusercontent.com/100352616/217992684-151e1ac4-c522-445f-aa10-e61a021a654b.png)

Any idea on how to solve this?

**Comment by seothemes** [comment]
@davidmadon thank you for reporting. This has been fixed in updates since
