### ISSUE TITLE
Broken after your "complete rebuild" version released 8 November 2023

### ISSUE THREAD

**Issue by samsong** [blockifywp/theme#42]
please upload the old version of blockify theme 1.2.9 & saasify 0.10

you have noted in changelog "complete rebuild" for both

this has broken our website. we cannot see the header footer & other pages.

each error revision suggests failure to retrieve the header footer components

Notice: Undefined index: slug in /wp-includes/class-wp-list-util.php on line 170

**Comment by seothemes** [comment]
Hi @samsong, it is possible to rollback to previous versions of the themes using the [WP Rollback](https://wordpress.org/plugins/wp-rollback/) plugin
